API_KEY = "PKK8IY7B4HFOXA91SGNF"
API_SECRET = "XHZGPrLgEAoTdsHdoa2k0QRwAM4uOWoQcpbMDxL0"
BASE_URL = "https://paper-api.alpaca.markets"

ALPACA_CREDS = {
    "API_KEY": API_KEY,
    "API_SECRET": API_SECRET,
    "PAPER": True
}

POLYGON_API_KEY = "NOVOKMmBnzyuTwJyKJKWGkayhJwNqpws"